Plugin API implementation
h4cktoria/Marinette pull request #7
Opened 2024-03-10 19:11 UTC by fmmaks666

Implements #5 

### Changes
- plugins.src - implementation for plugins
- examples - example plugins
- marilib.src - added new variables to `Var`

### TODO
- [ ] Translations
- [ ] Testing
- [ ] Better naming
- [ ] Implementations for all Permissions
- [ ] Preventing name collisions
### Future
- [ ] Command to manage plugins
- [ ] List of plugins to import at startup
- [ ] More APIs (Callbacks?)

2024-03-11 02:37 UTC, h4cktoria requested changes
Overall, there are quite a few things needs to be done:
- Plugin loading logic
- Command to handle plugins
- Better variables namings
- Translations
So, perhaps, push it to prototypes for now?

2024-03-11 02:37 UTC, h4cktoria commented on src/marilib.src
> -//
Why removing all of the // at the top of the comments? I'll change it back anyway xd It's sort of a habit commenting in MS

2024-03-11 02:37 UTC, h4cktoria commented on src/marilib.src
> +	"importPlugin": false,
Not sure what is this

2024-03-16 09:52 UTC, h4cktoria commented
Please pull origin before pull requesting so it won't change the stuff you didn't mean to change

2024-03-17 10:44 UTC, fmmaks666 commented
These PR had issues

2024-03-17 10:44 UTC, closed without merging